"""create topic table

Revision ID: 7f4e3e93e7e2
Revises: 6ff131b4a03f
Create Date: 2022-06-12 10:09:18.550965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4e3e93e7e2'
down_revision = '6ff131b4a03f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topic_topic_id'), 'topic', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_topic_name'), 'topic', ['topic_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_topic_id'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
