"""create topics_played table

Revision ID: 81bd8c897202
Revises: 9a90d9fdfec7
Create Date: 2022-06-14 02:53:18.951946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bd8c897202'
down_revision = '9a90d9fdfec7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_played',
    sa.Column('topic_played_id', sa.Integer(), nullable=False),
    sa.Column('played_by', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['played_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_played_id')
    )
    op.create_index(op.f('ix_topic_played_topic_played_id'), 'topic_played', ['topic_played_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_played_topic_played_id'), table_name='topic_played')
    op.drop_table('topic_played')
    # ### end Alembic commands ###
